// CLEAR
// FETCH
// RECEIVE
// REQUEST
// SAMPLE
// SELECT

// LANGUAGES
export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const RECEIVE_LANGUAGES = 'RECEIVE_LANGUAGES';

// FRAGMENT
export const FRAGMENT_REQUEST = 'FRAGMENT_REQUEST';
export const FRAGMENT_RESPONSE = 'FRAGMENT_RESPONSE';
export const RECEIVE_FRAGMENT = 'RECEIVE_FRAGMENT';
export const REQUEST_FRAGMENT = 'REQUEST_FRAGMENT';

// SEARCH
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_CLEARED = 'SEARCH_CLEARED';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';
export const RECEIVE_SLICES_HITS = 'RECEIVE_SLICES_HITS';

// REFERENCES
export const REQUEST_REFERENCES = 'REQUEST_REFERENCES';
export const RECEIVE_REFERENCES = 'RECEIVE_REFERENCES';

// REQUEST/RECEIVE
export const REQUEST_SLICES = 'REQUEST_SLICES';
export const RECEIVE_SLICES = 'RECEIVE_SLICES';
export const RECEIVE_SLICES_UPDATE = 'RECEIVE_UPDATE'; // TODO just RECEIVE_SLICES

export const REQUEST_SLICES_WITH_INSTANCES = 'REQUEST_SLICES_WITH_INSTANCES';
export const REQUEST_SLICES_SAMPLE = 'REQUEST_SLICES_SAMPLE';

// SELECT/UNSELECT
export const SELECT_SLICE = 'SELECT_SLICE';
export const UNSELECT_SLICE = 'UNSELECT_SLICE';

export const ADD_SLICE = 'ADD_SLICE';
export const REMOVE_SLICE = 'REMOVE_SLICE';

// UPLOAD/DOWNLOAD
export const DOWNLOAD_SLICE = 'DOWNLOAD_SLICE';
export const UPLOAD_SLICE = 'UPLOAD_SLICE';

// UPVOTE/DOWNVOTE
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';

export const REQUEST_UPVOTED = 'REQUEST_UPVOTED';
export const REQUEST_DOWNVOTED = 'REQUEST_DOWNVOTED';

// LIKE/UNLIKE
export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';

export const REQUEST_LIKED = 'REQUEST_LIKED';
export const REQUEST_UNLIKED = 'REQUEST_UNLIKED';

// FILTER STUFF
export const FILTER_WITH_INSTANCES = 'FILTER_WITH_INSTANCES';
export const FILTER_LIKED = 'FILTER_LIKED';
export const FILTER_BIG = 'FILTER_BIG';
export const FILTER_UPVOTED = 'FILTER_UPVOTED';
export const FILTER_DOWNVOTED = 'FILTER_DOWNVOTED';
export const FILTER_SELECTED = 'FILTER_SELECTED';

// CLEAR STUFF
export const CLEAR_SLICES = 'CLEAR_SLICES';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const CLEAR_SELECT = 'CLEAR_SELECT';
export const CLEAR_REFERENCES = 'CLEAR_REFERENCES';

// FORMS
export const POST_SUBMIT = 'POST_SUBMIT';
export const POST_RESPONSE = 'POST_RESPONSE';

// DISPLAY FILTERS
export const SHOW_SEARCHED = 'SHOW_SEARCHED';
export const SHOW_SELECTED = 'SHOW_SELECTED';
export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_FAVOURITE = 'SHOW_FAVOURITE';
export const SHOW_HASREFERENCES = 'SHOW_HASREFERENCES';

// SORT FILTERS
export const SORTBY_UPVOTES = 'SORTBY_UPVOTES';
