// CLEAR
// FETCH
// RECEIVE
// REQUEST
// SAMPLE
// SELECT

// LANGUAGES
export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const RECEIVE_LANGUAGES = 'RECEIVE_LANGUAGES';

// FRAGMENT
export const FRAGMENT_REQUEST = 'FRAGMENT_REQUEST';
export const FRAGMENT_RESPONSE = 'FRAGMENT_RESPONSE';
export const RECEIVE_FRAGMENT = 'RECEIVE_FRAGMENT';
export const REQUEST_FRAGMENT = 'REQUEST_FRAGMENT';

// SEARCH
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SEARCH_CLEARED = 'SEARCH_CLEARED';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';
export const RECEIVE_SLICES_HITS = 'RECEIVE_SLICES_HITS';

// REFERENCES
export const REQUEST_REFERENCES = 'REQUEST_REFERENCES';
export const RECEIVE_REFERENCES = 'RECEIVE_REFERENCES';

// SLICE
export const REQUEST_SLICES = 'REQUEST_SLICES';
export const RECEIVE_SLICES = 'RECEIVE_SLICES';
export const RECEIVE_SLICES_UPDATE = 'RECEIVE_SLICES_UPDATE';

export const REQUEST_SLICES_WITH_INSTANCES = 'REQUEST_SLICES_WITH_INSTANCES'; // clear selected and references
export const REQUEST_SLICES_SAMPLE = 'REQUEST_SLICES_SAMPLE';

export const SELECT_SLICE = 'SELECT_SLICE';

// UPVOTE/DOWNVOTE SLICES
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';

// LIKE/UNLIKE SLICES
export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const LIKE_SLICE = 'LIKE_SLICE';
export const UNLIKE_SLICE = 'UNLIKE_SLICE';
export const REQUEST_LIKED_SLICES = 'REQUEST_LIKED_SLICES';

// FILTER STUFF
export const FILTER_WITH_INSTANCES = 'FILTER_WITH_INSTANCES';
export const FILTER_LIKED = 'FILTER_LIKED';
export const FILTER_BIG = 'FILTER_BIG';
export const FILTER_UPVOTED = 'FILTER_UPVOTED';
export const FILTER_DOWNVOTED = 'FILTER_DOWNVOTED';
export const FILTER_SELECTED = 'FILTER_SELECTED';

// CLEAR STUFF
export const CLEAR_SLICES = 'CLEAR_SLICES';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const CLEAR_SELECT = 'CLEAR_SELECT';
