export const FETCH_SLICES = 'FETCH_SLICES';
export const RECEIVE_SLICES = 'RECEIVE_SLICES';
export const SAMPLE_SLICES = 'SAMPLE_SLICES';

export const SELECT_SLICE = 'SELECT_SLICE';
export const FETCH_SLICE = 'FETCH_SLICE';
export const RECEIVE_SLICE = 'RECEIVE_SLICE';
export const CROP_SELECTED_SLICE = 'CROP_SELECTED_SLICE';

export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const RECEIVE_LANGUAGES = 'RECEIVE_LANGUAGES';

export const FETCH_REFERENCES = 'FETCH_REFERENCES';
export const RECEIVE_REFERENCES = 'RECEIVE_REFERENCES';

export const REQUEST_FRAGMENT = 'REQUEST_FRAGMENT';
export const RECEIVE_FRAGMENT = 'RECEIVE_FRAGMENT';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
